package net.jarlehansen.protobuf.javame.examples.integration;

import java.io.IOException;

import net.jarlehansen.protobuf.javame.examples.generated.ExampleObject;
import net.jarlehansen.protobuf.javame.examples.generated.ExampleObjectImpl;

/**
 * Shows that the implementation with the Google Protocol buffer implementation
 * works. This example uses a byte array generated by the Java ME Protocol
 * Buffer implementation to create an instance of the Google Protocol Buffer
 * object.
 * 
 * Both the Java SE and Java ME version uses the same .proto-file to generate
 * the source code from.
 * 
 * @author Jarle Hansen hansjar@gmail.com
 * 
 */
public class GoogleProtobufIntegration {

	public static void main(String[] args) throws IOException {
		// Creates a byte array from the Java ME object
		final ExampleObject javaMeGenerated = ExampleObject.newBuilder().setId(41235).setName("John").setAddress(
				"London").build();
		final byte[] javaMeData = javaMeGenerated.toByteArray();

		/*
		 * Uses the byte array created by the Java ME object to populate a Java
		 * SE object. This new object is generated by the standard Google
		 * Protocol buffer implementation.
		 */
		final ExampleObjectImpl.ExampleObject javaSeGenerated = ExampleObjectImpl.ExampleObject.parseFrom(javaMeData);
		System.out.println(javaSeGenerated.toString());
	}
}
