// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/integration-test-enums/EnumTestJavaSe.proto

package net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase;

public final class EnumTestJavaSe {
  private EnumTestJavaSe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ExampleObjectEnum extends
      com.google.protobuf.GeneratedMessage {
    // Use ExampleObjectEnum.newBuilder() to construct.
    private ExampleObjectEnum() {
      initFields();
    }
    private ExampleObjectEnum(boolean noInit) {}
    
    private static final ExampleObjectEnum defaultInstance;
    public static ExampleObjectEnum getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExampleObjectEnum getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_ExampleObjectEnum_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_ExampleObjectEnum_fieldAccessorTable;
    }
    
    public enum Color
        implements com.google.protobuf.ProtocolMessageEnum {
      RED(0, 0),
      BLUE(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Color valueOf(int value) {
        switch (value) {
          case 0: return RED;
          case 1: return BLUE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Color>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Color>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Color>() {
              public Color findValueByNumber(int number) {
                return Color.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Color[] VALUES = {
        RED, BLUE, 
      };
      public static Color valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Color(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:net.jarlehansen.protobuf.javame.ExampleObjectEnum.Color)
    }
    
    public enum Direction
        implements com.google.protobuf.ProtocolMessageEnum {
      UP(0, 0),
      DOWN(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Direction valueOf(int value) {
        switch (value) {
          case 0: return UP;
          case 1: return DOWN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Direction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Direction>() {
              public Direction findValueByNumber(int number) {
                return Direction.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Direction[] VALUES = {
        UP, DOWN, 
      };
      public static Direction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Direction(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:net.jarlehansen.protobuf.javame.ExampleObjectEnum.Direction)
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string address = 3;
    public static final int ADDRESS_FIELD_NUMBER = 3;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // repeated .net.jarlehansen.protobuf.javame.ExampleObjectEnum.Color color = 4;
    public static final int COLOR_FIELD_NUMBER = 4;
    private java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color> color_ =
      java.util.Collections.emptyList();
    public java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color> getColorList() {
      return color_;
    }
    public int getColorCount() { return color_.size(); }
    public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color getColor(int index) {
      return color_.get(index);
    }
    
    // optional .net.jarlehansen.protobuf.javame.ExampleObjectEnum.Direction direction = 5;
    public static final int DIRECTION_FIELD_NUMBER = 5;
    private boolean hasDirection;
    private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction direction_;
    public boolean hasDirection() { return hasDirection; }
    public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction getDirection() { return direction_; }
    
    // repeated int64 number = 6;
    public static final int NUMBER_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Long> number_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Long> getNumberList() {
      return number_;
    }
    public int getNumberCount() { return number_.size(); }
    public long getNumber(int index) {
      return number_.get(index);
    }
    
    private void initFields() {
      direction_ = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction.UP;
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasAddress()) {
        output.writeString(3, getAddress());
      }
      for (net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color element : getColorList()) {
        output.writeEnum(4, element.getNumber());
      }
      if (hasDirection()) {
        output.writeEnum(5, getDirection().getNumber());
      }
      for (long element : getNumberList()) {
        output.writeInt64(6, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getAddress());
      }
      {
        int dataSize = 0;
        for (net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color element : getColorList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(element.getNumber());
        }
        size += dataSize;
        size += 1 * getColorList().size();
      }
      if (hasDirection()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, getDirection().getNumber());
      }
      {
        int dataSize = 0;
        for (long element : getNumberList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getNumberList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.color_ != java.util.Collections.EMPTY_LIST) {
          result.color_ =
            java.util.Collections.unmodifiableList(result.color_);
        }
        if (result.number_ != java.util.Collections.EMPTY_LIST) {
          result.number_ =
            java.util.Collections.unmodifiableList(result.number_);
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (!other.color_.isEmpty()) {
          if (result.color_.isEmpty()) {
            result.color_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color>();
          }
          result.color_.addAll(other.color_);
        }
        if (other.hasDirection()) {
          setDirection(other.getDirection());
        }
        if (!other.number_.isEmpty()) {
          if (result.number_.isEmpty()) {
            result.number_ = new java.util.ArrayList<java.lang.Long>();
          }
          result.number_.addAll(other.number_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              setAddress(input.readString());
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color value = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                addColor(value);
              }
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color value = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(4, rawValue);
                } else {
                  addColor(value);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction value = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                setDirection(value);
              }
              break;
            }
            case 48: {
              addNumber(input.readInt64());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addNumber(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string address = 3;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // repeated .net.jarlehansen.protobuf.javame.ExampleObjectEnum.Color color = 4;
      public java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color> getColorList() {
        return java.util.Collections.unmodifiableList(result.color_);
      }
      public int getColorCount() {
        return result.getColorCount();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color getColor(int index) {
        return result.getColor(index);
      }
      public Builder setColor(int index, net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.color_.set(index, value);
        return this;
      }
      public Builder addColor(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.color_.isEmpty()) {
          result.color_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color>();
        }
        result.color_.add(value);
        return this;
      }
      public Builder addAllColor(
          java.lang.Iterable<? extends net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color> values) {
        if (result.color_.isEmpty()) {
          result.color_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Color>();
        }
        super.addAll(values, result.color_);
        return this;
      }
      public Builder clearColor() {
        result.color_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .net.jarlehansen.protobuf.javame.ExampleObjectEnum.Direction direction = 5;
      public boolean hasDirection() {
        return result.hasDirection();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction getDirection() {
        return result.getDirection();
      }
      public Builder setDirection(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDirection = true;
        result.direction_ = value;
        return this;
      }
      public Builder clearDirection() {
        result.hasDirection = false;
        result.direction_ = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Direction.UP;
        return this;
      }
      
      // repeated int64 number = 6;
      public java.util.List<java.lang.Long> getNumberList() {
        return java.util.Collections.unmodifiableList(result.number_);
      }
      public int getNumberCount() {
        return result.getNumberCount();
      }
      public long getNumber(int index) {
        return result.getNumber(index);
      }
      public Builder setNumber(int index, long value) {
        result.number_.set(index, value);
        return this;
      }
      public Builder addNumber(long value) {
        if (result.number_.isEmpty()) {
          result.number_ = new java.util.ArrayList<java.lang.Long>();
        }
        result.number_.add(value);
        return this;
      }
      public Builder addAllNumber(
          java.lang.Iterable<? extends java.lang.Long> values) {
        if (result.number_.isEmpty()) {
          result.number_ = new java.util.ArrayList<java.lang.Long>();
        }
        super.addAll(values, result.number_);
        return this;
      }
      public Builder clearNumber() {
        result.number_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.ExampleObjectEnum)
    }
    
    static {
      defaultInstance = new ExampleObjectEnum(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.ExampleObjectEnum)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_ExampleObjectEnum_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_ExampleObjectEnum_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>src/test/resources/integration-test-en" +
      "ums/EnumTestJavaSe.proto\022\037net.jarlehanse" +
      "n.protobuf.javame\"\243\002\n\021ExampleObjectEnum\022" +
      "\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\017\n\007address\030\003 \001" +
      "(\t\022G\n\005color\030\004 \003(\01628.net.jarlehansen.prot" +
      "obuf.javame.ExampleObjectEnum.Color\022O\n\td" +
      "irection\030\005 \001(\0162<.net.jarlehansen.protobu" +
      "f.javame.ExampleObjectEnum.Direction\022\016\n\006" +
      "number\030\006 \003(\003\"\032\n\005Color\022\007\n\003RED\020\000\022\010\n\004BLUE\020\001" +
      "\"\035\n\tDirection\022\006\n\002UP\020\000\022\010\n\004DOWN\020\001BD\nBnet.j",
      "arlehansen.proto2javame.protobuf.integra" +
      "tion.tempfiles.javase"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_jarlehansen_protobuf_javame_ExampleObjectEnum_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_jarlehansen_protobuf_javame_ExampleObjectEnum_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_ExampleObjectEnum_descriptor,
              new java.lang.String[] { "Id", "Name", "Address", "Color", "Direction", "Number", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EnumTestJavaSe.ExampleObjectEnum.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
