// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/integration-test-nested-types/NestedTestJavaSe.proto

package net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase;

public final class NestedTestJavaSe {
  private NestedTestJavaSe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ExampleObjectNested extends
      com.google.protobuf.GeneratedMessage {
    // Use ExampleObjectNested.newBuilder() to construct.
    private ExampleObjectNested() {
      initFields();
    }
    private ExampleObjectNested(boolean noInit) {}
    
    private static final ExampleObjectNested defaultInstance;
    public static ExampleObjectNested getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExampleObjectNested getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNested_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNested_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string address = 3;
    public static final int ADDRESS_FIELD_NUMBER = 3;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // optional .net.jarlehansen.protobuf.javame.Number number = 4;
    public static final int NUMBER_FIELD_NUMBER = 4;
    private boolean hasNumber;
    private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number number_;
    public boolean hasNumber() { return hasNumber; }
    public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number getNumber() { return number_; }
    
    // required .net.jarlehansen.protobuf.javame.Identifier identifier = 5;
    public static final int IDENTIFIER_FIELD_NUMBER = 5;
    private boolean hasIdentifier;
    private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier identifier_;
    public boolean hasIdentifier() { return hasIdentifier; }
    public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier getIdentifier() { return identifier_; }
    
    private void initFields() {
      number_ = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.getDefaultInstance();
      identifier_ = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasName) return false;
      if (!hasIdentifier) return false;
      if (!getIdentifier().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasAddress()) {
        output.writeString(3, getAddress());
      }
      if (hasNumber()) {
        output.writeMessage(4, getNumber());
      }
      if (hasIdentifier()) {
        output.writeMessage(5, getIdentifier());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getAddress());
      }
      if (hasNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNumber());
      }
      if (hasIdentifier()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getIdentifier());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasNumber()) {
          mergeNumber(other.getNumber());
        }
        if (other.hasIdentifier()) {
          mergeIdentifier(other.getIdentifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              setAddress(input.readString());
              break;
            }
            case 34: {
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.Builder subBuilder = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.newBuilder();
              if (hasNumber()) {
                subBuilder.mergeFrom(getNumber());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNumber(subBuilder.buildPartial());
              break;
            }
            case 42: {
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.Builder subBuilder = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.newBuilder();
              if (hasIdentifier()) {
                subBuilder.mergeFrom(getIdentifier());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setIdentifier(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // required string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string address = 3;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // optional .net.jarlehansen.protobuf.javame.Number number = 4;
      public boolean hasNumber() {
        return result.hasNumber();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number getNumber() {
        return result.getNumber();
      }
      public Builder setNumber(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNumber = true;
        result.number_ = value;
        return this;
      }
      public Builder setNumber(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.Builder builderForValue) {
        result.hasNumber = true;
        result.number_ = builderForValue.build();
        return this;
      }
      public Builder mergeNumber(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number value) {
        if (result.hasNumber() &&
            result.number_ != net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.getDefaultInstance()) {
          result.number_ =
            net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.newBuilder(result.number_).mergeFrom(value).buildPartial();
        } else {
          result.number_ = value;
        }
        result.hasNumber = true;
        return this;
      }
      public Builder clearNumber() {
        result.hasNumber = false;
        result.number_ = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.getDefaultInstance();
        return this;
      }
      
      // required .net.jarlehansen.protobuf.javame.Identifier identifier = 5;
      public boolean hasIdentifier() {
        return result.hasIdentifier();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier getIdentifier() {
        return result.getIdentifier();
      }
      public Builder setIdentifier(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasIdentifier = true;
        result.identifier_ = value;
        return this;
      }
      public Builder setIdentifier(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.Builder builderForValue) {
        result.hasIdentifier = true;
        result.identifier_ = builderForValue.build();
        return this;
      }
      public Builder mergeIdentifier(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier value) {
        if (result.hasIdentifier() &&
            result.identifier_ != net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.getDefaultInstance()) {
          result.identifier_ =
            net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.newBuilder(result.identifier_).mergeFrom(value).buildPartial();
        } else {
          result.identifier_ = value;
        }
        result.hasIdentifier = true;
        return this;
      }
      public Builder clearIdentifier() {
        result.hasIdentifier = false;
        result.identifier_ = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.ExampleObjectNested)
    }
    
    static {
      defaultInstance = new ExampleObjectNested(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.ExampleObjectNested)
  }
  
  public static final class Number extends
      com.google.protobuf.GeneratedMessage {
    // Use Number.newBuilder() to construct.
    private Number() {
      initFields();
    }
    private Number(boolean noInit) {}
    
    private static final Number defaultInstance;
    public static Number getDefaultInstance() {
      return defaultInstance;
    }
    
    public Number getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_Number_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_Number_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.Number)
    }
    
    static {
      defaultInstance = new Number(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.Number)
  }
  
  public static final class Identifier extends
      com.google.protobuf.GeneratedMessage {
    // Use Identifier.newBuilder() to construct.
    private Identifier() {
      initFields();
    }
    private Identifier(boolean noInit) {}
    
    private static final Identifier defaultInstance;
    public static Identifier getDefaultInstance() {
      return defaultInstance;
    }
    
    public Identifier getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_Identifier_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_Identifier_fieldAccessorTable;
    }
    
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private long id_ = 0L;
    public boolean hasId() { return hasId; }
    public long getId() { return id_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt64(1, getId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, getId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // required int64 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public long getId() {
        return result.getId();
      }
      public Builder setId(long value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.Identifier)
    }
    
    static {
      defaultInstance = new Identifier(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.Identifier)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNested_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNested_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_Number_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_Number_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_Identifier_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_Identifier_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nGsrc/test/resources/integration-test-ne" +
      "sted-types/NestedTestJavaSe.proto\022\037net.j" +
      "arlehansen.protobuf.javame\"\272\001\n\023ExampleOb" +
      "jectNested\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t\022\017\n\007" +
      "address\030\003 \001(\t\0227\n\006number\030\004 \001(\0132\'.net.jarl" +
      "ehansen.protobuf.javame.Number\022?\n\nidenti" +
      "fier\030\005 \002(\0132+.net.jarlehansen.protobuf.ja" +
      "vame.Identifier\"\024\n\006Number\022\n\n\002id\030\001 \001(\005\"\030\n" +
      "\nIdentifier\022\n\n\002id\030\001 \002(\003BD\nBnet.jarlehans" +
      "en.proto2javame.protobuf.integration.tem",
      "pfiles.javase"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNested_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNested_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNested_descriptor,
              new java.lang.String[] { "Id", "Name", "Address", "Number", "Identifier", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.ExampleObjectNested.Builder.class);
          internal_static_net_jarlehansen_protobuf_javame_Number_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_jarlehansen_protobuf_javame_Number_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_Number_descriptor,
              new java.lang.String[] { "Id", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Number.Builder.class);
          internal_static_net_jarlehansen_protobuf_javame_Identifier_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_net_jarlehansen_protobuf_javame_Identifier_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_Identifier_descriptor,
              new java.lang.String[] { "Id", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedTestJavaSe.Identifier.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
