// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/integration-test-nested-types/EmployeeGoalJavaSe.proto

package net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase;

public final class EmployeeGoal {
  private EmployeeGoal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class EmployeeGoalJavaSe extends
      com.google.protobuf.GeneratedMessage {
    // Use EmployeeGoalJavaSe.newBuilder() to construct.
    private EmployeeGoalJavaSe() {
      initFields();
    }
    private EmployeeGoalJavaSe(boolean noInit) {}
    
    private static final EmployeeGoalJavaSe defaultInstance;
    public static EmployeeGoalJavaSe getDefaultInstance() {
      return defaultInstance;
    }
    
    public EmployeeGoalJavaSe getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalJavaSe_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalJavaSe_fieldAccessorTable;
    }
    
    // required float actualValue = 1;
    public static final int ACTUALVALUE_FIELD_NUMBER = 1;
    private boolean hasActualValue;
    private float actualValue_ = 0F;
    public boolean hasActualValue() { return hasActualValue; }
    public float getActualValue() { return actualValue_; }
    
    // repeated .net.jarlehansen.protobuf.javame.EmployeeGoalCommentJavaSe employeeGoalComments = 2;
    public static final int EMPLOYEEGOALCOMMENTS_FIELD_NUMBER = 2;
    private java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe> employeeGoalComments_ =
      java.util.Collections.emptyList();
    public java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe> getEmployeeGoalCommentsList() {
      return employeeGoalComments_;
    }
    public int getEmployeeGoalCommentsCount() { return employeeGoalComments_.size(); }
    public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe getEmployeeGoalComments(int index) {
      return employeeGoalComments_.get(index);
    }
    
    // optional int32 criticality = 3;
    public static final int CRITICALITY_FIELD_NUMBER = 3;
    private boolean hasCriticality;
    private int criticality_ = 0;
    public boolean hasCriticality() { return hasCriticality; }
    public int getCriticality() { return criticality_; }
    
    // optional int64 dueDate = 4;
    public static final int DUEDATE_FIELD_NUMBER = 4;
    private boolean hasDueDate;
    private long dueDate_ = 0L;
    public boolean hasDueDate() { return hasDueDate; }
    public long getDueDate() { return dueDate_; }
    
    // optional string key = 5;
    public static final int KEY_FIELD_NUMBER = 5;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // optional string name = 6;
    public static final int NAME_FIELD_NUMBER = 6;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional float percentCompleted = 7;
    public static final int PERCENTCOMPLETED_FIELD_NUMBER = 7;
    private boolean hasPercentCompleted;
    private float percentCompleted_ = 0F;
    public boolean hasPercentCompleted() { return hasPercentCompleted; }
    public float getPercentCompleted() { return percentCompleted_; }
    
    // optional float percentProgress = 8;
    public static final int PERCENTPROGRESS_FIELD_NUMBER = 8;
    private boolean hasPercentProgress;
    private float percentProgress_ = 0F;
    public boolean hasPercentProgress() { return hasPercentProgress; }
    public float getPercentProgress() { return percentProgress_; }
    
    // optional int64 startDate = 9;
    public static final int STARTDATE_FIELD_NUMBER = 9;
    private boolean hasStartDate;
    private long startDate_ = 0L;
    public boolean hasStartDate() { return hasStartDate; }
    public long getStartDate() { return startDate_; }
    
    // optional string status = 10;
    public static final int STATUS_FIELD_NUMBER = 10;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    // optional float targetValue = 11;
    public static final int TARGETVALUE_FIELD_NUMBER = 11;
    private boolean hasTargetValue;
    private float targetValue_ = 0F;
    public boolean hasTargetValue() { return hasTargetValue; }
    public float getTargetValue() { return targetValue_; }
    
    // optional string type = 12;
    public static final int TYPE_FIELD_NUMBER = 12;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasActualValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasActualValue()) {
        output.writeFloat(1, getActualValue());
      }
      for (net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe element : getEmployeeGoalCommentsList()) {
        output.writeMessage(2, element);
      }
      if (hasCriticality()) {
        output.writeInt32(3, getCriticality());
      }
      if (hasDueDate()) {
        output.writeInt64(4, getDueDate());
      }
      if (hasKey()) {
        output.writeString(5, getKey());
      }
      if (hasName()) {
        output.writeString(6, getName());
      }
      if (hasPercentCompleted()) {
        output.writeFloat(7, getPercentCompleted());
      }
      if (hasPercentProgress()) {
        output.writeFloat(8, getPercentProgress());
      }
      if (hasStartDate()) {
        output.writeInt64(9, getStartDate());
      }
      if (hasStatus()) {
        output.writeString(10, getStatus());
      }
      if (hasTargetValue()) {
        output.writeFloat(11, getTargetValue());
      }
      if (hasType()) {
        output.writeString(12, getType());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasActualValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, getActualValue());
      }
      for (net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe element : getEmployeeGoalCommentsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasCriticality()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getCriticality());
      }
      if (hasDueDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, getDueDate());
      }
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getKey());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getName());
      }
      if (hasPercentCompleted()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, getPercentCompleted());
      }
      if (hasPercentProgress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, getPercentProgress());
      }
      if (hasStartDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, getStartDate());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getStatus());
      }
      if (hasTargetValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(11, getTargetValue());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getType());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.employeeGoalComments_ != java.util.Collections.EMPTY_LIST) {
          result.employeeGoalComments_ =
            java.util.Collections.unmodifiableList(result.employeeGoalComments_);
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe.getDefaultInstance()) return this;
        if (other.hasActualValue()) {
          setActualValue(other.getActualValue());
        }
        if (!other.employeeGoalComments_.isEmpty()) {
          if (result.employeeGoalComments_.isEmpty()) {
            result.employeeGoalComments_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe>();
          }
          result.employeeGoalComments_.addAll(other.employeeGoalComments_);
        }
        if (other.hasCriticality()) {
          setCriticality(other.getCriticality());
        }
        if (other.hasDueDate()) {
          setDueDate(other.getDueDate());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPercentCompleted()) {
          setPercentCompleted(other.getPercentCompleted());
        }
        if (other.hasPercentProgress()) {
          setPercentProgress(other.getPercentProgress());
        }
        if (other.hasStartDate()) {
          setStartDate(other.getStartDate());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasTargetValue()) {
          setTargetValue(other.getTargetValue());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 13: {
              setActualValue(input.readFloat());
              break;
            }
            case 18: {
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.Builder subBuilder = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEmployeeGoalComments(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setCriticality(input.readInt32());
              break;
            }
            case 32: {
              setDueDate(input.readInt64());
              break;
            }
            case 42: {
              setKey(input.readString());
              break;
            }
            case 50: {
              setName(input.readString());
              break;
            }
            case 61: {
              setPercentCompleted(input.readFloat());
              break;
            }
            case 69: {
              setPercentProgress(input.readFloat());
              break;
            }
            case 72: {
              setStartDate(input.readInt64());
              break;
            }
            case 82: {
              setStatus(input.readString());
              break;
            }
            case 93: {
              setTargetValue(input.readFloat());
              break;
            }
            case 98: {
              setType(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required float actualValue = 1;
      public boolean hasActualValue() {
        return result.hasActualValue();
      }
      public float getActualValue() {
        return result.getActualValue();
      }
      public Builder setActualValue(float value) {
        result.hasActualValue = true;
        result.actualValue_ = value;
        return this;
      }
      public Builder clearActualValue() {
        result.hasActualValue = false;
        result.actualValue_ = 0F;
        return this;
      }
      
      // repeated .net.jarlehansen.protobuf.javame.EmployeeGoalCommentJavaSe employeeGoalComments = 2;
      public java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe> getEmployeeGoalCommentsList() {
        return java.util.Collections.unmodifiableList(result.employeeGoalComments_);
      }
      public int getEmployeeGoalCommentsCount() {
        return result.getEmployeeGoalCommentsCount();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe getEmployeeGoalComments(int index) {
        return result.getEmployeeGoalComments(index);
      }
      public Builder setEmployeeGoalComments(int index, net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.employeeGoalComments_.set(index, value);
        return this;
      }
      public Builder setEmployeeGoalComments(int index, net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.Builder builderForValue) {
        result.employeeGoalComments_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEmployeeGoalComments(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.employeeGoalComments_.isEmpty()) {
          result.employeeGoalComments_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe>();
        }
        result.employeeGoalComments_.add(value);
        return this;
      }
      public Builder addEmployeeGoalComments(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.Builder builderForValue) {
        if (result.employeeGoalComments_.isEmpty()) {
          result.employeeGoalComments_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe>();
        }
        result.employeeGoalComments_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEmployeeGoalComments(
          java.lang.Iterable<? extends net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe> values) {
        if (result.employeeGoalComments_.isEmpty()) {
          result.employeeGoalComments_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe>();
        }
        super.addAll(values, result.employeeGoalComments_);
        return this;
      }
      public Builder clearEmployeeGoalComments() {
        result.employeeGoalComments_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional int32 criticality = 3;
      public boolean hasCriticality() {
        return result.hasCriticality();
      }
      public int getCriticality() {
        return result.getCriticality();
      }
      public Builder setCriticality(int value) {
        result.hasCriticality = true;
        result.criticality_ = value;
        return this;
      }
      public Builder clearCriticality() {
        result.hasCriticality = false;
        result.criticality_ = 0;
        return this;
      }
      
      // optional int64 dueDate = 4;
      public boolean hasDueDate() {
        return result.hasDueDate();
      }
      public long getDueDate() {
        return result.getDueDate();
      }
      public Builder setDueDate(long value) {
        result.hasDueDate = true;
        result.dueDate_ = value;
        return this;
      }
      public Builder clearDueDate() {
        result.hasDueDate = false;
        result.dueDate_ = 0L;
        return this;
      }
      
      // optional string key = 5;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // optional string name = 6;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional float percentCompleted = 7;
      public boolean hasPercentCompleted() {
        return result.hasPercentCompleted();
      }
      public float getPercentCompleted() {
        return result.getPercentCompleted();
      }
      public Builder setPercentCompleted(float value) {
        result.hasPercentCompleted = true;
        result.percentCompleted_ = value;
        return this;
      }
      public Builder clearPercentCompleted() {
        result.hasPercentCompleted = false;
        result.percentCompleted_ = 0F;
        return this;
      }
      
      // optional float percentProgress = 8;
      public boolean hasPercentProgress() {
        return result.hasPercentProgress();
      }
      public float getPercentProgress() {
        return result.getPercentProgress();
      }
      public Builder setPercentProgress(float value) {
        result.hasPercentProgress = true;
        result.percentProgress_ = value;
        return this;
      }
      public Builder clearPercentProgress() {
        result.hasPercentProgress = false;
        result.percentProgress_ = 0F;
        return this;
      }
      
      // optional int64 startDate = 9;
      public boolean hasStartDate() {
        return result.hasStartDate();
      }
      public long getStartDate() {
        return result.getStartDate();
      }
      public Builder setStartDate(long value) {
        result.hasStartDate = true;
        result.startDate_ = value;
        return this;
      }
      public Builder clearStartDate() {
        result.hasStartDate = false;
        result.startDate_ = 0L;
        return this;
      }
      
      // optional string status = 10;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // optional float targetValue = 11;
      public boolean hasTargetValue() {
        return result.hasTargetValue();
      }
      public float getTargetValue() {
        return result.getTargetValue();
      }
      public Builder setTargetValue(float value) {
        result.hasTargetValue = true;
        result.targetValue_ = value;
        return this;
      }
      public Builder clearTargetValue() {
        result.hasTargetValue = false;
        result.targetValue_ = 0F;
        return this;
      }
      
      // optional string type = 12;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.EmployeeGoalJavaSe)
    }
    
    static {
      defaultInstance = new EmployeeGoalJavaSe(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.EmployeeGoalJavaSe)
  }
  
  public static final class EmployeeGoalCommentJavaSe extends
      com.google.protobuf.GeneratedMessage {
    // Use EmployeeGoalCommentJavaSe.newBuilder() to construct.
    private EmployeeGoalCommentJavaSe() {
      initFields();
    }
    private EmployeeGoalCommentJavaSe(boolean noInit) {}
    
    private static final EmployeeGoalCommentJavaSe defaultInstance;
    public static EmployeeGoalCommentJavaSe getDefaultInstance() {
      return defaultInstance;
    }
    
    public EmployeeGoalCommentJavaSe getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalCommentJavaSe_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalCommentJavaSe_fieldAccessorTable;
    }
    
    // optional string author = 1;
    public static final int AUTHOR_FIELD_NUMBER = 1;
    private boolean hasAuthor;
    private java.lang.String author_ = "";
    public boolean hasAuthor() { return hasAuthor; }
    public java.lang.String getAuthor() { return author_; }
    
    // optional string comment = 2;
    public static final int COMMENT_FIELD_NUMBER = 2;
    private boolean hasComment;
    private java.lang.String comment_ = "";
    public boolean hasComment() { return hasComment; }
    public java.lang.String getComment() { return comment_; }
    
    // optional int64 createDate = 3;
    public static final int CREATEDATE_FIELD_NUMBER = 3;
    private boolean hasCreateDate;
    private long createDate_ = 0L;
    public boolean hasCreateDate() { return hasCreateDate; }
    public long getCreateDate() { return createDate_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAuthor()) {
        output.writeString(1, getAuthor());
      }
      if (hasComment()) {
        output.writeString(2, getComment());
      }
      if (hasCreateDate()) {
        output.writeInt64(3, getCreateDate());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAuthor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAuthor());
      }
      if (hasComment()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getComment());
      }
      if (hasCreateDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, getCreateDate());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.getDefaultInstance()) return this;
        if (other.hasAuthor()) {
          setAuthor(other.getAuthor());
        }
        if (other.hasComment()) {
          setComment(other.getComment());
        }
        if (other.hasCreateDate()) {
          setCreateDate(other.getCreateDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAuthor(input.readString());
              break;
            }
            case 18: {
              setComment(input.readString());
              break;
            }
            case 24: {
              setCreateDate(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // optional string author = 1;
      public boolean hasAuthor() {
        return result.hasAuthor();
      }
      public java.lang.String getAuthor() {
        return result.getAuthor();
      }
      public Builder setAuthor(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAuthor = true;
        result.author_ = value;
        return this;
      }
      public Builder clearAuthor() {
        result.hasAuthor = false;
        result.author_ = getDefaultInstance().getAuthor();
        return this;
      }
      
      // optional string comment = 2;
      public boolean hasComment() {
        return result.hasComment();
      }
      public java.lang.String getComment() {
        return result.getComment();
      }
      public Builder setComment(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasComment = true;
        result.comment_ = value;
        return this;
      }
      public Builder clearComment() {
        result.hasComment = false;
        result.comment_ = getDefaultInstance().getComment();
        return this;
      }
      
      // optional int64 createDate = 3;
      public boolean hasCreateDate() {
        return result.hasCreateDate();
      }
      public long getCreateDate() {
        return result.getCreateDate();
      }
      public Builder setCreateDate(long value) {
        result.hasCreateDate = true;
        result.createDate_ = value;
        return this;
      }
      public Builder clearCreateDate() {
        result.hasCreateDate = false;
        result.createDate_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.EmployeeGoalCommentJavaSe)
    }
    
    static {
      defaultInstance = new EmployeeGoalCommentJavaSe(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.EmployeeGoalCommentJavaSe)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalJavaSe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalJavaSe_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalCommentJavaSe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalCommentJavaSe_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nIsrc/test/resources/integration-test-ne" +
      "sted-types/EmployeeGoalJavaSe.proto\022\037net" +
      ".jarlehansen.protobuf.javame\"\275\002\n\022Employe" +
      "eGoalJavaSe\022\023\n\013actualValue\030\001 \002(\002\022X\n\024empl" +
      "oyeeGoalComments\030\002 \003(\0132:.net.jarlehansen" +
      ".protobuf.javame.EmployeeGoalCommentJava" +
      "Se\022\023\n\013criticality\030\003 \001(\005\022\017\n\007dueDate\030\004 \001(\003" +
      "\022\013\n\003key\030\005 \001(\t\022\014\n\004name\030\006 \001(\t\022\030\n\020percentCo" +
      "mpleted\030\007 \001(\002\022\027\n\017percentProgress\030\010 \001(\002\022\021" +
      "\n\tstartDate\030\t \001(\003\022\016\n\006status\030\n \001(\t\022\023\n\013tar",
      "getValue\030\013 \001(\002\022\014\n\004type\030\014 \001(\t\"P\n\031Employee" +
      "GoalCommentJavaSe\022\016\n\006author\030\001 \001(\t\022\017\n\007com" +
      "ment\030\002 \001(\t\022\022\n\ncreateDate\030\003 \001(\003BR\nBnet.ja" +
      "rlehansen.proto2javame.protobuf.integrat" +
      "ion.tempfiles.javaseB\014EmployeeGoal"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalJavaSe_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalJavaSe_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalJavaSe_descriptor,
              new java.lang.String[] { "ActualValue", "EmployeeGoalComments", "Criticality", "DueDate", "Key", "Name", "PercentCompleted", "PercentProgress", "StartDate", "Status", "TargetValue", "Type", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalJavaSe.Builder.class);
          internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalCommentJavaSe_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalCommentJavaSe_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_EmployeeGoalCommentJavaSe_descriptor,
              new java.lang.String[] { "Author", "Comment", "CreateDate", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.EmployeeGoal.EmployeeGoalCommentJavaSe.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
