// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/integration-test-nested-types/NestedListTestJavaSe.proto

package net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase;

public final class NestedListTestJavaSe {
  private NestedListTestJavaSe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ExampleObjectNestedListJavaSe extends
      com.google.protobuf.GeneratedMessage {
    // Use ExampleObjectNestedListJavaSe.newBuilder() to construct.
    private ExampleObjectNestedListJavaSe() {
      initFields();
    }
    private ExampleObjectNestedListJavaSe(boolean noInit) {}
    
    private static final ExampleObjectNestedListJavaSe defaultInstance;
    public static ExampleObjectNestedListJavaSe getDefaultInstance() {
      return defaultInstance;
    }
    
    public ExampleObjectNestedListJavaSe getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNestedListJavaSe_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNestedListJavaSe_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // repeated .net.jarlehansen.protobuf.javame.Person persons = 2;
    public static final int PERSONS_FIELD_NUMBER = 2;
    private java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person> persons_ =
      java.util.Collections.emptyList();
    public java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person> getPersonsList() {
      return persons_;
    }
    public int getPersonsCount() { return persons_.size(); }
    public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person getPersons(int index) {
      return persons_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      for (net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person element : getPersonsList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      for (net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person element : getPersonsList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      for (net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person element : getPersonsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.persons_ != java.util.Collections.EMPTY_LIST) {
          result.persons_ =
            java.util.Collections.unmodifiableList(result.persons_);
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.persons_.isEmpty()) {
          if (result.persons_.isEmpty()) {
            result.persons_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person>();
          }
          result.persons_.addAll(other.persons_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.Builder subBuilder = net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPersons(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // repeated .net.jarlehansen.protobuf.javame.Person persons = 2;
      public java.util.List<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person> getPersonsList() {
        return java.util.Collections.unmodifiableList(result.persons_);
      }
      public int getPersonsCount() {
        return result.getPersonsCount();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person getPersons(int index) {
        return result.getPersons(index);
      }
      public Builder setPersons(int index, net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.persons_.set(index, value);
        return this;
      }
      public Builder setPersons(int index, net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.Builder builderForValue) {
        result.persons_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPersons(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.persons_.isEmpty()) {
          result.persons_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person>();
        }
        result.persons_.add(value);
        return this;
      }
      public Builder addPersons(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.Builder builderForValue) {
        if (result.persons_.isEmpty()) {
          result.persons_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person>();
        }
        result.persons_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPersons(
          java.lang.Iterable<? extends net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person> values) {
        if (result.persons_.isEmpty()) {
          result.persons_ = new java.util.ArrayList<net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person>();
        }
        super.addAll(values, result.persons_);
        return this;
      }
      public Builder clearPersons() {
        result.persons_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.ExampleObjectNestedListJavaSe)
    }
    
    static {
      defaultInstance = new ExampleObjectNestedListJavaSe(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.ExampleObjectNestedListJavaSe)
  }
  
  public static final class Person extends
      com.google.protobuf.GeneratedMessage {
    // Use Person.newBuilder() to construct.
    private Person() {
      initFields();
    }
    private Person(boolean noInit) {}
    
    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }
    
    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_Person_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.internal_static_net_jarlehansen_protobuf_javame_Person_fieldAccessorTable;
    }
    
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasName()) {
        output.writeString(1, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.protobuf.javame.Person)
    }
    
    static {
      defaultInstance = new Person(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.protobuf.javame.Person)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNestedListJavaSe_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNestedListJavaSe_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_protobuf_javame_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_protobuf_javame_Person_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nKsrc/test/resources/integration-test-ne" +
      "sted-types/NestedListTestJavaSe.proto\022\037n" +
      "et.jarlehansen.protobuf.javame\"e\n\035Exampl" +
      "eObjectNestedListJavaSe\022\n\n\002id\030\001 \002(\005\0228\n\007p" +
      "ersons\030\002 \003(\0132\'.net.jarlehansen.protobuf." +
      "javame.Person\"\026\n\006Person\022\014\n\004name\030\001 \002(\tBD\n" +
      "Bnet.jarlehansen.proto2javame.protobuf.i" +
      "ntegration.tempfiles.javase"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNestedListJavaSe_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNestedListJavaSe_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_ExampleObjectNestedListJavaSe_descriptor,
              new java.lang.String[] { "Id", "Persons", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.ExampleObjectNestedListJavaSe.Builder.class);
          internal_static_net_jarlehansen_protobuf_javame_Person_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_net_jarlehansen_protobuf_javame_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_protobuf_javame_Person_descriptor,
              new java.lang.String[] { "Name", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.NestedListTestJavaSe.Person.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
