// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/test/resources/integration-test/UpdatedIntegrationTestJavaSe.proto

package net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase;

public final class UpdatedIntegrationTestObjectProto {
  private UpdatedIntegrationTestObjectProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class UpdatedIntegrationTestObject extends
      com.google.protobuf.GeneratedMessage {
    // Use UpdatedIntegrationTestObject.newBuilder() to construct.
    private UpdatedIntegrationTestObject() {
      initFields();
    }
    private UpdatedIntegrationTestObject(boolean noInit) {}
    
    private static final UpdatedIntegrationTestObject defaultInstance;
    public static UpdatedIntegrationTestObject getDefaultInstance() {
      return defaultInstance;
    }
    
    public UpdatedIntegrationTestObject getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.internal_static_net_jarlehansen_proto2javame_UpdatedIntegrationTestObject_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.internal_static_net_jarlehansen_proto2javame_UpdatedIntegrationTestObject_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // required int64 longNumber = 2;
    public static final int LONGNUMBER_FIELD_NUMBER = 2;
    private boolean hasLongNumber;
    private long longNumber_ = 0L;
    public boolean hasLongNumber() { return hasLongNumber; }
    public long getLongNumber() { return longNumber_; }
    
    // repeated string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private java.util.List<java.lang.String> name_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getNameList() {
      return name_;
    }
    public int getNameCount() { return name_.size(); }
    public java.lang.String getName(int index) {
      return name_.get(index);
    }
    
    // required bytes bytesObject = 4;
    public static final int BYTESOBJECT_FIELD_NUMBER = 4;
    private boolean hasBytesObject;
    private com.google.protobuf.ByteString bytesObject_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasBytesObject() { return hasBytesObject; }
    public com.google.protobuf.ByteString getBytesObject() { return bytesObject_; }
    
    // required float floatObject = 5;
    public static final int FLOATOBJECT_FIELD_NUMBER = 5;
    private boolean hasFloatObject;
    private float floatObject_ = 0F;
    public boolean hasFloatObject() { return hasFloatObject; }
    public float getFloatObject() { return floatObject_; }
    
    // optional bool boolObj = 6;
    public static final int BOOLOBJ_FIELD_NUMBER = 6;
    private boolean hasBoolObj;
    private boolean boolObj_ = false;
    public boolean hasBoolObj() { return hasBoolObj; }
    public boolean getBoolObj() { return boolObj_; }
    
    // required double amount = 7;
    public static final int AMOUNT_FIELD_NUMBER = 7;
    private boolean hasAmount;
    private double amount_ = 0D;
    public boolean hasAmount() { return hasAmount; }
    public double getAmount() { return amount_; }
    
    // required bytes newField = 8;
    public static final int NEWFIELD_FIELD_NUMBER = 8;
    private boolean hasNewField;
    private com.google.protobuf.ByteString newField_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasNewField() { return hasNewField; }
    public com.google.protobuf.ByteString getNewField() { return newField_; }
    
    // required int32 newField2 = 9;
    public static final int NEWFIELD2_FIELD_NUMBER = 9;
    private boolean hasNewField2;
    private int newField2_ = 0;
    public boolean hasNewField2() { return hasNewField2; }
    public int getNewField2() { return newField2_; }
    
    // required int64 newField3 = 10;
    public static final int NEWFIELD3_FIELD_NUMBER = 10;
    private boolean hasNewField3;
    private long newField3_ = 0L;
    public boolean hasNewField3() { return hasNewField3; }
    public long getNewField3() { return newField3_; }
    
    // required string newField4 = 11;
    public static final int NEWFIELD4_FIELD_NUMBER = 11;
    private boolean hasNewField4;
    private java.lang.String newField4_ = "";
    public boolean hasNewField4() { return hasNewField4; }
    public java.lang.String getNewField4() { return newField4_; }
    
    // required float newField5 = 12;
    public static final int NEWFIELD5_FIELD_NUMBER = 12;
    private boolean hasNewField5;
    private float newField5_ = 0F;
    public boolean hasNewField5() { return hasNewField5; }
    public float getNewField5() { return newField5_; }
    
    // required bool newField6 = 13;
    public static final int NEWFIELD6_FIELD_NUMBER = 13;
    private boolean hasNewField6;
    private boolean newField6_ = false;
    public boolean hasNewField6() { return hasNewField6; }
    public boolean getNewField6() { return newField6_; }
    
    // required double newField7 = 14;
    public static final int NEWFIELD7_FIELD_NUMBER = 14;
    private boolean hasNewField7;
    private double newField7_ = 0D;
    public boolean hasNewField7() { return hasNewField7; }
    public double getNewField7() { return newField7_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasLongNumber) return false;
      if (!hasBytesObject) return false;
      if (!hasFloatObject) return false;
      if (!hasAmount) return false;
      if (!hasNewField) return false;
      if (!hasNewField2) return false;
      if (!hasNewField3) return false;
      if (!hasNewField4) return false;
      if (!hasNewField5) return false;
      if (!hasNewField6) return false;
      if (!hasNewField7) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasLongNumber()) {
        output.writeInt64(2, getLongNumber());
      }
      for (java.lang.String element : getNameList()) {
        output.writeString(3, element);
      }
      if (hasBytesObject()) {
        output.writeBytes(4, getBytesObject());
      }
      if (hasFloatObject()) {
        output.writeFloat(5, getFloatObject());
      }
      if (hasBoolObj()) {
        output.writeBool(6, getBoolObj());
      }
      if (hasAmount()) {
        output.writeDouble(7, getAmount());
      }
      if (hasNewField()) {
        output.writeBytes(8, getNewField());
      }
      if (hasNewField2()) {
        output.writeInt32(9, getNewField2());
      }
      if (hasNewField3()) {
        output.writeInt64(10, getNewField3());
      }
      if (hasNewField4()) {
        output.writeString(11, getNewField4());
      }
      if (hasNewField5()) {
        output.writeFloat(12, getNewField5());
      }
      if (hasNewField6()) {
        output.writeBool(13, getNewField6());
      }
      if (hasNewField7()) {
        output.writeDouble(14, getNewField7());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasLongNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getLongNumber());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getNameList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      if (hasBytesObject()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getBytesObject());
      }
      if (hasFloatObject()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, getFloatObject());
      }
      if (hasBoolObj()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, getBoolObj());
      }
      if (hasAmount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, getAmount());
      }
      if (hasNewField()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getNewField());
      }
      if (hasNewField2()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, getNewField2());
      }
      if (hasNewField3()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, getNewField3());
      }
      if (hasNewField4()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getNewField4());
      }
      if (hasNewField5()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, getNewField5());
      }
      if (hasNewField6()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(13, getNewField6());
      }
      if (hasNewField7()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, getNewField7());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject result;
      
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject();
        return builder;
      }
      
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.name_ != java.util.Collections.EMPTY_LIST) {
          result.name_ =
            java.util.Collections.unmodifiableList(result.name_);
        }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLongNumber()) {
          setLongNumber(other.getLongNumber());
        }
        if (!other.name_.isEmpty()) {
          if (result.name_.isEmpty()) {
            result.name_ = new java.util.ArrayList<java.lang.String>();
          }
          result.name_.addAll(other.name_);
        }
        if (other.hasBytesObject()) {
          setBytesObject(other.getBytesObject());
        }
        if (other.hasFloatObject()) {
          setFloatObject(other.getFloatObject());
        }
        if (other.hasBoolObj()) {
          setBoolObj(other.getBoolObj());
        }
        if (other.hasAmount()) {
          setAmount(other.getAmount());
        }
        if (other.hasNewField()) {
          setNewField(other.getNewField());
        }
        if (other.hasNewField2()) {
          setNewField2(other.getNewField2());
        }
        if (other.hasNewField3()) {
          setNewField3(other.getNewField3());
        }
        if (other.hasNewField4()) {
          setNewField4(other.getNewField4());
        }
        if (other.hasNewField5()) {
          setNewField5(other.getNewField5());
        }
        if (other.hasNewField6()) {
          setNewField6(other.getNewField6());
        }
        if (other.hasNewField7()) {
          setNewField7(other.getNewField7());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 16: {
              setLongNumber(input.readInt64());
              break;
            }
            case 26: {
              addName(input.readString());
              break;
            }
            case 34: {
              setBytesObject(input.readBytes());
              break;
            }
            case 45: {
              setFloatObject(input.readFloat());
              break;
            }
            case 48: {
              setBoolObj(input.readBool());
              break;
            }
            case 57: {
              setAmount(input.readDouble());
              break;
            }
            case 66: {
              setNewField(input.readBytes());
              break;
            }
            case 72: {
              setNewField2(input.readInt32());
              break;
            }
            case 80: {
              setNewField3(input.readInt64());
              break;
            }
            case 90: {
              setNewField4(input.readString());
              break;
            }
            case 101: {
              setNewField5(input.readFloat());
              break;
            }
            case 104: {
              setNewField6(input.readBool());
              break;
            }
            case 113: {
              setNewField7(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // required int64 longNumber = 2;
      public boolean hasLongNumber() {
        return result.hasLongNumber();
      }
      public long getLongNumber() {
        return result.getLongNumber();
      }
      public Builder setLongNumber(long value) {
        result.hasLongNumber = true;
        result.longNumber_ = value;
        return this;
      }
      public Builder clearLongNumber() {
        result.hasLongNumber = false;
        result.longNumber_ = 0L;
        return this;
      }
      
      // repeated string name = 3;
      public java.util.List<java.lang.String> getNameList() {
        return java.util.Collections.unmodifiableList(result.name_);
      }
      public int getNameCount() {
        return result.getNameCount();
      }
      public java.lang.String getName(int index) {
        return result.getName(index);
      }
      public Builder setName(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.name_.set(index, value);
        return this;
      }
      public Builder addName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.name_.isEmpty()) {
          result.name_ = new java.util.ArrayList<java.lang.String>();
        }
        result.name_.add(value);
        return this;
      }
      public Builder addAllName(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.name_.isEmpty()) {
          result.name_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.name_);
        return this;
      }
      public Builder clearName() {
        result.name_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required bytes bytesObject = 4;
      public boolean hasBytesObject() {
        return result.hasBytesObject();
      }
      public com.google.protobuf.ByteString getBytesObject() {
        return result.getBytesObject();
      }
      public Builder setBytesObject(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBytesObject = true;
        result.bytesObject_ = value;
        return this;
      }
      public Builder clearBytesObject() {
        result.hasBytesObject = false;
        result.bytesObject_ = getDefaultInstance().getBytesObject();
        return this;
      }
      
      // required float floatObject = 5;
      public boolean hasFloatObject() {
        return result.hasFloatObject();
      }
      public float getFloatObject() {
        return result.getFloatObject();
      }
      public Builder setFloatObject(float value) {
        result.hasFloatObject = true;
        result.floatObject_ = value;
        return this;
      }
      public Builder clearFloatObject() {
        result.hasFloatObject = false;
        result.floatObject_ = 0F;
        return this;
      }
      
      // optional bool boolObj = 6;
      public boolean hasBoolObj() {
        return result.hasBoolObj();
      }
      public boolean getBoolObj() {
        return result.getBoolObj();
      }
      public Builder setBoolObj(boolean value) {
        result.hasBoolObj = true;
        result.boolObj_ = value;
        return this;
      }
      public Builder clearBoolObj() {
        result.hasBoolObj = false;
        result.boolObj_ = false;
        return this;
      }
      
      // required double amount = 7;
      public boolean hasAmount() {
        return result.hasAmount();
      }
      public double getAmount() {
        return result.getAmount();
      }
      public Builder setAmount(double value) {
        result.hasAmount = true;
        result.amount_ = value;
        return this;
      }
      public Builder clearAmount() {
        result.hasAmount = false;
        result.amount_ = 0D;
        return this;
      }
      
      // required bytes newField = 8;
      public boolean hasNewField() {
        return result.hasNewField();
      }
      public com.google.protobuf.ByteString getNewField() {
        return result.getNewField();
      }
      public Builder setNewField(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNewField = true;
        result.newField_ = value;
        return this;
      }
      public Builder clearNewField() {
        result.hasNewField = false;
        result.newField_ = getDefaultInstance().getNewField();
        return this;
      }
      
      // required int32 newField2 = 9;
      public boolean hasNewField2() {
        return result.hasNewField2();
      }
      public int getNewField2() {
        return result.getNewField2();
      }
      public Builder setNewField2(int value) {
        result.hasNewField2 = true;
        result.newField2_ = value;
        return this;
      }
      public Builder clearNewField2() {
        result.hasNewField2 = false;
        result.newField2_ = 0;
        return this;
      }
      
      // required int64 newField3 = 10;
      public boolean hasNewField3() {
        return result.hasNewField3();
      }
      public long getNewField3() {
        return result.getNewField3();
      }
      public Builder setNewField3(long value) {
        result.hasNewField3 = true;
        result.newField3_ = value;
        return this;
      }
      public Builder clearNewField3() {
        result.hasNewField3 = false;
        result.newField3_ = 0L;
        return this;
      }
      
      // required string newField4 = 11;
      public boolean hasNewField4() {
        return result.hasNewField4();
      }
      public java.lang.String getNewField4() {
        return result.getNewField4();
      }
      public Builder setNewField4(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNewField4 = true;
        result.newField4_ = value;
        return this;
      }
      public Builder clearNewField4() {
        result.hasNewField4 = false;
        result.newField4_ = getDefaultInstance().getNewField4();
        return this;
      }
      
      // required float newField5 = 12;
      public boolean hasNewField5() {
        return result.hasNewField5();
      }
      public float getNewField5() {
        return result.getNewField5();
      }
      public Builder setNewField5(float value) {
        result.hasNewField5 = true;
        result.newField5_ = value;
        return this;
      }
      public Builder clearNewField5() {
        result.hasNewField5 = false;
        result.newField5_ = 0F;
        return this;
      }
      
      // required bool newField6 = 13;
      public boolean hasNewField6() {
        return result.hasNewField6();
      }
      public boolean getNewField6() {
        return result.getNewField6();
      }
      public Builder setNewField6(boolean value) {
        result.hasNewField6 = true;
        result.newField6_ = value;
        return this;
      }
      public Builder clearNewField6() {
        result.hasNewField6 = false;
        result.newField6_ = false;
        return this;
      }
      
      // required double newField7 = 14;
      public boolean hasNewField7() {
        return result.hasNewField7();
      }
      public double getNewField7() {
        return result.getNewField7();
      }
      public Builder setNewField7(double value) {
        result.hasNewField7 = true;
        result.newField7_ = value;
        return this;
      }
      public Builder clearNewField7() {
        result.hasNewField7 = false;
        result.newField7_ = 0D;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:net.jarlehansen.proto2javame.UpdatedIntegrationTestObject)
    }
    
    static {
      defaultInstance = new UpdatedIntegrationTestObject(true);
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:net.jarlehansen.proto2javame.UpdatedIntegrationTestObject)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_net_jarlehansen_proto2javame_UpdatedIntegrationTestObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_net_jarlehansen_proto2javame_UpdatedIntegrationTestObject_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nFsrc/test/resources/integration-test/Up" +
      "datedIntegrationTestJavaSe.proto\022\034net.ja" +
      "rlehansen.proto2javame\"\233\002\n\034UpdatedIntegr" +
      "ationTestObject\022\n\n\002id\030\001 \002(\005\022\022\n\nlongNumbe" +
      "r\030\002 \002(\003\022\014\n\004name\030\003 \003(\t\022\023\n\013bytesObject\030\004 \002" +
      "(\014\022\023\n\013floatObject\030\005 \002(\002\022\017\n\007boolObj\030\006 \001(\010" +
      "\022\016\n\006amount\030\007 \002(\001\022\020\n\010newField\030\010 \002(\014\022\021\n\tne" +
      "wField2\030\t \002(\005\022\021\n\tnewField3\030\n \002(\003\022\021\n\tnewF" +
      "ield4\030\013 \002(\t\022\021\n\tnewField5\030\014 \002(\002\022\021\n\tnewFie" +
      "ld6\030\r \002(\010\022\021\n\tnewField7\030\016 \002(\001Bg\nBnet.jarl",
      "ehansen.proto2javame.protobuf.integratio" +
      "n.tempfiles.javaseB!UpdatedIntegrationTe" +
      "stObjectProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_net_jarlehansen_proto2javame_UpdatedIntegrationTestObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_net_jarlehansen_proto2javame_UpdatedIntegrationTestObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_net_jarlehansen_proto2javame_UpdatedIntegrationTestObject_descriptor,
              new java.lang.String[] { "Id", "LongNumber", "Name", "BytesObject", "FloatObject", "BoolObj", "Amount", "NewField", "NewField2", "NewField3", "NewField4", "NewField5", "NewField6", "NewField7", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.javase.UpdatedIntegrationTestObjectProto.UpdatedIntegrationTestObject.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
