// Generated by the protocol buffer compiler.  DO NOT EDIT!

package net.jarlehansen.proto2javame.protobuf.integration.tempfiles;

public final class JunitTestMainObjectProto {
  private JunitTestMainObjectProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class JunitTestMainObject extends
      com.google.protobuf.GeneratedMessage {
    // Use JunitTestMainObject.newBuilder() to construct.
    private JunitTestMainObject() {}
    
    private static final JunitTestMainObject defaultInstance = new JunitTestMainObject();
    public static JunitTestMainObject getDefaultInstance() {
      return defaultInstance;
    }
    
    public JunitTestMainObject getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.internal_static_this_is_not_used_JunitTestMainObject_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.internal_static_this_is_not_used_JunitTestMainObject_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject.newBuilder()
      private Builder() {}
      
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject();
      
      @Override
      protected net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject.getDescriptor();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject getDefaultInstanceForType() {
        return net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject.getDefaultInstance();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject) {
          return mergeFrom((net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject other) {
        if (other == net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
    }
    
    static {
      net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_this_is_not_used_JunitTestMainObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_this_is_not_used_JunitTestMainObject_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n8src/test/resources/tempfiles/JunitStan" +
      "dardTestMain.proto\022\020this.is.not.used\"!\n\023" +
      "JunitTestMainObject\022\n\n\002id\030\001 \002(\005BW\n;net.j" +
      "arlehansen.proto2javame.protobuf.integra" +
      "tion.tempfilesB\030JunitTestMainObjectProto";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_this_is_not_used_JunitTestMainObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_this_is_not_used_JunitTestMainObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_this_is_not_used_JunitTestMainObject_descriptor,
              new java.lang.String[] { "Id", },
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject.class,
              net.jarlehansen.proto2javame.protobuf.integration.tempfiles.JunitTestMainObjectProto.JunitTestMainObject.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
